name: Database

on:
  push:
    branches:
    - master
    paths:
    - "*"
    - "!README.md"
  schedule:
    - cron:  "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install sqlite
      run: sudo apt-get install sqlite3
    - name: Authenticate to GitHub API
      run: echo ${{ secrets.github_token }} | pipenv run github-to-sqlite auth
    - name: Build database
      run: make
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        branch: master
        github_token: ${{ secrets.github_token }}
        github_pat: ${{ secrets.github_token }}
        commit_author: "gareth@morethanseven.net"
        commit_message: Updated database with latest content
