name: Build database

on:
  push:
    branches:
    - master
    paths:
    - "*"
    - "!README.md"
    - "!cloud-native-tools.db"
  schedule:
    - cron:  "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install sqlite
      run: sudo apt-get install sqlite3
    - name: Authenticate to GitHub API
      run: echo ${{ secrets.github_token }} | pipenv run github-to-sqlite auth
    - name: Build database
      run: make sort build
    - name: Commit latest database changes
      run: |-
        git config --global user.email "action-bot@example.com"
        git config --global user.name "Action"
        git diff --quiet || (git add cloud-native-tools.db tools && git commit -m "Updated database with latest entries")
        git push
    - name: Save database as an artifact
      uses: actions/upload-artifact@v1
      with:
        name: Cloud Native tools database
        path: cloud-native-tools.db
